feat: add config option to highlight dir with devicons active
tamago324/lir.nvim pull request #76
Opened 2023-01-07 14:59 UTC by opalmay

only makes a difference with devicons on.
highlight_dirnames_with_devicons = false:
![image](https://user-images.githubusercontent.com/65673442/211156955-229c0afc-a546-443f-bfa3-09c92aa70485.png)
highlight_dirnames_with_devicons = true:
![image](https://user-images.githubusercontent.com/65673442/211157044-14c0b612-1003-49bb-b99c-d475fd7a6bc4.png)

2023-01-09 09:39 UTC, tamago324 commented
@opalmay 
Thank you very much.
I would like the configuration to be structured like this:

```lua
require'lir'.setup {
  devicons = {
    enable = false,
    highlight_dirnames = false
  },
  ...
```

If it seems difficult, I would like to implement it myself.

2023-01-09 10:38 UTC, opalmay commented
> @opalmay Thank you very much. I would like the configuration to be structured like this:
> 
> ```lua
> require'lir'.setup {
>   devicons = {
>     enable = false,
>     highlight_dirnames = false
>   },
>   ...
> ```
> 
> If it seems difficult, I would like to implement it myself.

Done :)
Beware that it's a breaking change.

2023-01-10 00:37 UTC, tamago324 commented
Please add processing when the `devicons` setting value is empty and a warning message when the `devicons_enable` setting value is specified.

```diff
  function config.set_default_values(opts)
    config.values = vim.tbl_deep_extend("force", defaults_values, opts or {})
  
    -- For an empty table
    if vim.tbl_isempty(config.values.float) then
      config.values.float = defaults_values.float
    elseif vim.tbl_isempty(config.values.float.curdir_window) then
      config.values.float.curdir_window = defaults_values.float.curdir_window
    end
  
+   if vim.tbl_isempty(config.values.devicons) then
+     config.values.devicons = defaults_values.devicons
+   end
+ 
+   if config.values.devicons_enable then
+     config.values.devicons.enable = true
+     -- echo waring
+     vim.api.nvim_echo({ { '\n', 'Normal' } }, false, {})
+     vim.api.nvim_echo(
+       { { '[lir.nvim] `devicons_enable` is deprecated. Use `devicons.enable` instead. \n', 'WarningMsg' } },
+       false, {})
+   end
  end
  

```

2023-01-10 00:39 UTC, tamago324 requested changes

2023-01-10 00:39 UTC, tamago324 commented on lua/lir/config.lua
> +---@field devicons          table
Please make the correction here.

```diff
- ---@field devicons          table
+ ---@field devicons          lir.config.values.devicons
```

2023-01-11 15:43 UTC, tamago324 reviewed
I am sorry for repeating myself.
Please change `devicons.hishlight_dirnames` to `devicons.hishlight_dirname`.
The `float.curdir_window.highlight_dirname` doesn't have the `s` and I want to make it the same.

2023-01-11 15:43 UTC, tamago324 approved these changes

2023-01-11 22:49 UTC, tamago324 approved these changes
LGTM

2023-01-11 22:49 UTC, merged

2023-01-11 22:50 UTC, tamago324 commented
Thank you!